FROM node:18-alpine
WORKDIR /app
COPY apps/frontend/package.json apps/frontend/tsconfig.json ./
COPY apps/frontend/pages ./pages
COPY apps/frontend/styles ./styles
RUN npm install --prefix ./
EXPOSE 3000
CMD ["npx", "next", "start", "-p", "3000"]
